user www-data;
worker_processes auto;
pid /run/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Создаем детальный формат логов
    log_format detailed '$remote_addr - $remote_user [$time_local] '
                        '"$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" '
                        'RT=$request_time '
                        'AUTH="$http_authorization" COOKIE="$http_cookie"';

    access_log /var/log/nginx/access.log detailed; # Включаем его
    error_log /var/log/nginx/error.log debug;      # Включаем дебаг-уровень

    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    include /etc/nginx/conf.d/*.conf;
}
